# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files {{C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/player.coe}}
read_mem {{C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/player_1.mem}}
read_verilog -library xil_defaultlib {
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/player_sprite_rom.v}
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/tile_map.v}
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/player_sprite.v}
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/vga_sync.v}
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/renderer.v}
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/game_tick.v}
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/bullet.v}
  {C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/sources_1/new/top_module.v}
}
read_xdc {{C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/constrs_1/new/Ganiga_constraints.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Songwit Rueangsawat/Desktop/CODE/Git/ganiga/Ganiga.srcs/constrs_1/new/Ganiga_constraints.xdc}}]

synth_design -top top_module -part xc7a35ticpg236-1L
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
