# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Y2_ALL/CPE_digital/GAniga/Ganiga.cache/wt [current_project]
set_property parent.project_path D:/Y2_ALL/CPE_digital/GAniga/Ganiga.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/player.coe
add_files -quiet D:/Y2_ALL/CPE_digital/GAniga/Ganiga.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files D:/Y2_ALL/CPE_digital/GAniga/Ganiga.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
read_mem D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/player_1.mem
read_verilog -library xil_defaultlib {
  D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/player_sprite.v
  D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/vga_sync.v
  D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/renderer.v
  D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/game_tick.v
  D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/bullet.v
  D:/Y2_ALL/CPE_digital/GAniga/Ganiga.srcs/sources_1/new/top_module.v
}
read_xdc D:/Y2_ALL/CPE_digital/lab10/Ganiga/ganiga.srcs/constrs_1/new/Ganiga_constraints.xdc
set_property used_in_implementation false [get_files D:/Y2_ALL/CPE_digital/lab10/Ganiga/ganiga.srcs/constrs_1/new/Ganiga_constraints.xdc]

synth_design -top top_module -part xc7a35ticpg236-1L
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
